const RECEIVE_POSTS = "RECEIVE_POSTS_SYMBOL_DETAILS";
const REQUEST_POSTS = "REQUEST_POSTS_SYMBOL_DETAILS";
const RECEIVE_CHART = "RECEIVE_CHART";

export { RECEIVE_POSTS, REQUEST_POSTS, RECEIVE_CHART };
