const RECEIVE_POSTS = "RECEIVE_POSTS_SECTORL_DETAILS";
const REQUEST_POSTS = "REQUEST_POSTS_SECTOR_DETAILS";
const RECEIVE_POSTS_ERROR = "RECEIVE_POSTS_ERROR";

export { RECEIVE_POSTS, REQUEST_POSTS, RECEIVE_POSTS_ERROR };
