const SELECT_DEPARTMENT = 'SELECT_DEPARTMENT';
const SELECT_SYMBOL = 'SELECT_SYMBOL';
const ADD_TO_WATCH_LIST = 'ADD_TO_WATCH_LIST';
const DEL_FROM_WATCH_LIST = 'DEL_FROM_WATCH_LIST';
const LOG_IN = 'LOG_IN';
const LOG_OUT = 'LOG_OUT';
const IS_USER_EXIST = 'IS_USER_EXIST';
const REGISTRATION = 'REGISTRATION';

export {
  ADD_TO_WATCH_LIST,
  DEL_FROM_WATCH_LIST,
  SELECT_DEPARTMENT,
  SELECT_SYMBOL,
  LOG_IN,
  LOG_OUT,
  REGISTRATION,
  IS_USER_EXIST,
};
