const SELECT_DEPARTMENT = 'SELECT_DEPARTMENT';
const SELECT_SYMBOL = 'SELECT_SYMBOL';
const ADD_TO_WATCH_LIST = 'ADD_TO_WATCH_LIST';
const DEL_FROM_WATCH_LIST = 'DEL_FROM_WATCH_LIST';

export {
    ADD_TO_WATCH_LIST,
    DEL_FROM_WATCH_LIST,
    SELECT_DEPARTMENT,
    SELECT_SYMBOL,
};